preprocessing:
  prescale:
    algorithm: Bilinear
    imageHeight: 1000
    imageWidth: 1000
  
  operations:
    equalizeHistogram: true
    reduceColors: false
    colorReducerRatio: 10
 
segmentation:
  maskImage: false

  useRed: true
  redMask: 
    lowerHue: -20
    upperHue: 20

    lowerSaturation: 150
    upperSaturation: 255

    lowerValue: 100
    upperValue: 255

  useBlue: true
  blueMask:
    lowerHue: 220
    upperHue: 260

    lowerSaturation: 100
    upperSaturation: 255

    lowerValue: 0
    upperValue: 255

  useWhite: true
  whiteMask:
    lowerHue: 0
    upperHue: 360

    lowerSaturation: 0
    upperSaturation: 50

    lowerValue: 200
    upperValue: 255

  useYellow: true
  yellowMask:
    lowerHue: 20
    upperHue: 60

    lowerSaturation: 100
    upperSaturation: 255

    lowerValue: 180
    upperValue: 255
