equalizeHistogram: true

reduceColors: false # czy redukować kolory

colorReducerRatio: 1 # współczynnik redukcji kolorów

maskImage: true # czy maskowac

bicubicRatio: -0.75

# rozmiar analizowanego zdjęcia
imageHeight: 1200
imageWidth: 200

# parametry czerwonej maski
useRed: true
redMask: 
  lowerHue: -20
  upperHue: 20

  lowerSaturation: 150
  upperSaturation: 255

  lowerValue: 100
  upperValue: 255

# parametry niebieskiej maski
useBlue: true
blueMask:
  lowerHue: 220
  upperHue: 260

  lowerSaturation: 100
  upperSaturation: 255

  lowerValue: 0
  upperValue: 255

# parametry białej maski
useWhite: true
whiteMask:
  lowerHue: 0
  upperHue: 360

  lowerSaturation: 0
  upperSaturation: 50

  lowerValue: 200
  upperValue: 255

# parametry żółtej maski
useYellow: true
yellowMask:
  lowerHue: 20
  upperHue: 60

  lowerSaturation: 100
  upperSaturation: 255

  lowerValue: 180
  upperValue: 255
