preprocessing:
  prescale:
    algorithm: Bicubic
    imageHeight: 900
    imageWidth: 1200
  
  operations:
    equalizeHistogram: true
    reduceColors: false
    colorReducerRatio: 10
 
segmentation:
  maskImage: true

  useRed: true
  redMask: 
    lowerHue: -20
    upperHue: 20

    lowerSaturation: 150
    upperSaturation: 255

    lowerValue: 100
    upperValue: 255

  useBlue: true
  blueMask:
    lowerHue: 220
    upperHue: 300

    lowerSaturation: 70
    upperSaturation: 255

    lowerValue: 0
    upperValue: 255

  useWhite: true
  whiteMask:
    lowerHue: 0
    upperHue: 360

    lowerSaturation: 0
    upperSaturation: 75

    lowerValue: 100
    upperValue: 255

  useYellow: true
  yellowMask:
    lowerHue: 20
    upperHue: 60

    lowerSaturation: 80
    upperSaturation: 255

    lowerValue: 150
    upperValue: 255
